kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: registry.internal.hoffmeister.biz/diztortion/iperf3
      registry: registry.internal.hoffmeister.biz
      auto_tag: true

  - name: clair
    image: jmccann/drone-clair:1
    settings:
      url: https://clair.internal.hoffmeister.biz
      username: ${CLAIR_USERNAME}
      password: ${CLAIR_PASSWORD}
      scan_image: registry.internal.hoffmeister.biz/diztortion/iperf3
