kind: pipeline
type: kubernetes
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: docker-registry.hoffmeister.biz/diztortion/iperf3
      registry: docker-registry.hoffmeister.biz
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest
      auto_tag: true
